-- =====================================================
-- BILLING & PAYMENT DOMAIN TABLES
-- =====================================================

-- Invoices
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    outlet_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    invoice_number VARCHAR(50) NOT NULL,
    invoice_date DATE NOT NULL,
    invoice_time TIME NOT NULL,
    customer_id BIGINT UNSIGNED,
    customer_name VARCHAR(100),
    customer_phone VARCHAR(20),
    customer_email VARCHAR(255),
    customer_gstin VARCHAR(20),
    customer_address TEXT,
    billing_address TEXT,
    subtotal DECIMAL(12, 2) NOT NULL,
    discount_amount DECIMAL(12, 2) DEFAULT 0,
    taxable_amount DECIMAL(12, 2) NOT NULL,
    cgst_amount DECIMAL(12, 2) DEFAULT 0,
    sgst_amount DECIMAL(12, 2) DEFAULT 0,
    igst_amount DECIMAL(12, 2) DEFAULT 0,
    vat_amount DECIMAL(12, 2) DEFAULT 0,
    cess_amount DECIMAL(12, 2) DEFAULT 0,
    total_tax DECIMAL(12, 2) DEFAULT 0,
    service_charge DECIMAL(12, 2) DEFAULT 0,
    packaging_charge DECIMAL(12, 2) DEFAULT 0,
    delivery_charge DECIMAL(12, 2) DEFAULT 0,
    round_off DECIMAL(5, 2) DEFAULT 0,
    grand_total DECIMAL(12, 2) NOT NULL,
    amount_in_words VARCHAR(255),
    payment_status ENUM('pending', 'partial', 'paid', 'refunded') DEFAULT 'pending',
    tax_breakup JSON,
    hsn_summary JSON,
    notes TEXT,
    terms_conditions TEXT,
    is_cancelled BOOLEAN DEFAULT FALSE,
    cancelled_at DATETIME,
    cancelled_by BIGINT UNSIGNED,
    cancel_reason VARCHAR(255),
    generated_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_invoice_number_outlet (outlet_id, invoice_number),
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    INDEX idx_invoices_outlet (outlet_id),
    INDEX idx_invoices_order (order_id),
    INDEX idx_invoices_number (invoice_number),
    INDEX idx_invoices_date (invoice_date),
    INDEX idx_invoices_customer (customer_id),
    INDEX idx_invoices_status (payment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Payments
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    outlet_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    invoice_id BIGINT UNSIGNED,
    payment_number VARCHAR(50),
    payment_mode ENUM('cash', 'card', 'upi', 'wallet', 'credit', 'complimentary', 'split') NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    tip_amount DECIMAL(10, 2) DEFAULT 0,
    total_amount DECIMAL(12, 2) NOT NULL,
    status ENUM('pending', 'completed', 'failed', 'refunded', 'cancelled') DEFAULT 'pending',
    transaction_id VARCHAR(100),
    reference_number VARCHAR(100),
    card_last_four VARCHAR(4),
    card_type VARCHAR(20),
    upi_id VARCHAR(100),
    wallet_name VARCHAR(50),
    bank_name VARCHAR(100),
    payment_gateway VARCHAR(50),
    gateway_response JSON,
    notes VARCHAR(255),
    received_by BIGINT UNSIGNED NOT NULL,
    verified_by BIGINT UNSIGNED,
    verified_at DATETIME,
    refunded_at DATETIME,
    refund_amount DECIMAL(12, 2) DEFAULT 0,
    refund_reason VARCHAR(255),
    refund_reference VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL,
    INDEX idx_payments_outlet (outlet_id),
    INDEX idx_payments_order (order_id),
    INDEX idx_payments_invoice (invoice_id),
    INDEX idx_payments_mode (payment_mode),
    INDEX idx_payments_status (status),
    INDEX idx_payments_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Split payments
CREATE TABLE IF NOT EXISTS split_payments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    payment_id BIGINT UNSIGNED NOT NULL,
    payment_mode ENUM('cash', 'card', 'upi', 'wallet', 'credit') NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    transaction_id VARCHAR(100),
    reference_number VARCHAR(100),
    card_last_four VARCHAR(4),
    upi_id VARCHAR(100),
    notes VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
    INDEX idx_split_payments_payment (payment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Duplicate bill logs
CREATE TABLE IF NOT EXISTS duplicate_bill_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_id BIGINT UNSIGNED NOT NULL,
    outlet_id BIGINT UNSIGNED NOT NULL,
    duplicate_number INT NOT NULL,
    reason VARCHAR(255),
    printed_by BIGINT UNSIGNED NOT NULL,
    printed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE,
    INDEX idx_duplicate_bills_invoice (invoice_id),
    INDEX idx_duplicate_bills_outlet (outlet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Applied discounts on orders
CREATE TABLE IF NOT EXISTS order_discounts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED,
    discount_id BIGINT UNSIGNED,
    discount_code VARCHAR(50),
    discount_name VARCHAR(100),
    discount_type ENUM('percentage', 'flat', 'item_level', 'bill_level') NOT NULL,
    discount_value DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(12, 2) NOT NULL,
    applied_on ENUM('subtotal', 'item', 'category') DEFAULT 'subtotal',
    approved_by BIGINT UNSIGNED,
    approval_reason VARCHAR(255),
    created_by BIGINT UNSIGNED,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE SET NULL,
    FOREIGN KEY (discount_id) REFERENCES discounts(id) ON DELETE SET NULL,
    INDEX idx_order_discounts_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Refunds
CREATE TABLE IF NOT EXISTS refunds (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    outlet_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    payment_id BIGINT UNSIGNED NOT NULL,
    refund_number VARCHAR(50),
    refund_amount DECIMAL(12, 2) NOT NULL,
    refund_mode ENUM('cash', 'card', 'upi', 'wallet', 'original_mode') NOT NULL,
    status ENUM('pending', 'approved', 'processed', 'rejected') DEFAULT 'pending',
    reason VARCHAR(255) NOT NULL,
    reference_number VARCHAR(100),
    requested_by BIGINT UNSIGNED NOT NULL,
    approved_by BIGINT UNSIGNED,
    approved_at DATETIME,
    processed_at DATETIME,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
    INDEX idx_refunds_outlet (outlet_id),
    INDEX idx_refunds_order (order_id),
    INDEX idx_refunds_payment (payment_id),
    INDEX idx_refunds_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Cash drawer transactions
CREATE TABLE IF NOT EXISTS cash_drawer (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    outlet_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    transaction_type ENUM('opening', 'closing', 'cash_in', 'cash_out', 'sale', 'refund', 'expense', 'deposit') NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    balance_before DECIMAL(12, 2),
    balance_after DECIMAL(12, 2),
    reference_type VARCHAR(50),
    reference_id BIGINT UNSIGNED,
    description VARCHAR(255),
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE,
    INDEX idx_cash_drawer_outlet (outlet_id),
    INDEX idx_cash_drawer_user (user_id),
    INDEX idx_cash_drawer_type (transaction_type),
    INDEX idx_cash_drawer_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Day sessions (opening/closing)
CREATE TABLE IF NOT EXISTS day_sessions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    outlet_id BIGINT UNSIGNED NOT NULL,
    session_date DATE NOT NULL,
    opening_time DATETIME,
    closing_time DATETIME,
    opening_cash DECIMAL(12, 2) DEFAULT 0,
    closing_cash DECIMAL(12, 2) DEFAULT 0,
    expected_cash DECIMAL(12, 2) DEFAULT 0,
    cash_variance DECIMAL(12, 2) DEFAULT 0,
    total_sales DECIMAL(12, 2) DEFAULT 0,
    total_orders INT DEFAULT 0,
    total_cash_sales DECIMAL(12, 2) DEFAULT 0,
    total_card_sales DECIMAL(12, 2) DEFAULT 0,
    total_upi_sales DECIMAL(12, 2) DEFAULT 0,
    total_discounts DECIMAL(12, 2) DEFAULT 0,
    total_refunds DECIMAL(12, 2) DEFAULT 0,
    total_cancellations DECIMAL(12, 2) DEFAULT 0,
    status ENUM('open', 'closing', 'closed') DEFAULT 'open',
    opened_by BIGINT UNSIGNED,
    closed_by BIGINT UNSIGNED,
    variance_notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_day_session (outlet_id, session_date),
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE,
    INDEX idx_day_sessions_outlet (outlet_id),
    INDEX idx_day_sessions_date (session_date),
    INDEX idx_day_sessions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customers
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    outlet_id BIGINT UNSIGNED,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(255),
    alternate_phone VARCHAR(20),
    date_of_birth DATE,
    anniversary_date DATE,
    gender ENUM('male', 'female', 'other'),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    gstin VARCHAR(20),
    company_name VARCHAR(150),
    loyalty_points INT DEFAULT 0,
    total_visits INT DEFAULT 0,
    total_spent DECIMAL(12, 2) DEFAULT 0,
    average_bill DECIMAL(10, 2) DEFAULT 0,
    last_visit_date DATE,
    tags VARCHAR(255),
    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_customers_outlet (outlet_id),
    INDEX idx_customers_phone (phone),
    INDEX idx_customers_email (email),
    INDEX idx_customers_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
